# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: trusty
cache: packages

addons:
  apt:
    packages:
      - gdal-bin
      - libgdal-dev
      - libproj-dev
